#!/usr/bin/env python3
"""Delete shared test sandboxes and clean up .env file.

This script:
1. Reads sandbox IDs from environment
2. Deletes both worker and service sandboxes
3. Removes the auto-generated variables from .env

Usage:
    cd tests && make test-teardown
    # or directly:
    python tests/scripts/test_teardown.py
"""

import os
import sys
from pathlib import Path

# Add src to path (tests/scripts -> tests -> root -> src)
src_path = Path(__file__).parent.parent.parent / "src"
sys.path.insert(0, str(src_path))

from dotenv import load_dotenv

# Load existing .env
load_dotenv()

# Variables managed by test-setup
MANAGED_VARS = [
    "SHARED_WORKER_SANDBOX_ID",
    "SHARED_SERVICE_SANDBOX_ID",
    "SANDBOX_API_URL",
    "SANDBOX_API_TOKEN",
    "TEST_APP_ID",
]


def clean_env_file():
    """Remove auto-generated variables from .env file."""
    env_path = Path(__file__).parent.parent.parent / ".env"

    if not env_path.exists():
        print("  No .env file found, nothing to clean")
        return

    # Read existing content
    existing_content = env_path.read_text()

    # Remove managed variables and the header comment
    lines = existing_content.split("\n")
    filtered_lines = []
    skip_next_empty = False

    for line in lines:
        # Skip the auto-generated header
        if line.strip() == "# Shared Test Sandboxes (auto-generated by make test-setup)":
            skip_next_empty = True
            continue
        # Skip managed variables
        if any(line.startswith(f"{var}=") for var in MANAGED_VARS):
            continue
        # Skip empty line right after header removal
        if skip_next_empty and line.strip() == "":
            skip_next_empty = False
            continue
        skip_next_empty = False
        filtered_lines.append(line)

    # Remove trailing empty lines
    while filtered_lines and filtered_lines[-1].strip() == "":
        filtered_lines.pop()

    # Write back
    new_content = "\n".join(filtered_lines)
    if new_content and not new_content.endswith("\n"):
        new_content += "\n"

    env_path.write_text(new_content)
    print(f"  Cleaned {env_path}")


def main():
    """Delete shared test sandboxes."""
    from do_app_sandbox import Sandbox
    from do_app_sandbox.exceptions import SandboxNotFoundError

    print("=" * 60)
    print("  Cleaning Up Shared Test Sandboxes")
    print("=" * 60)

    worker_id = os.environ.get("SHARED_WORKER_SANDBOX_ID")
    service_id = os.environ.get("SHARED_SERVICE_SANDBOX_ID")

    if not worker_id and not service_id:
        print("\nNo shared sandboxes found in environment.")
        print("Nothing to clean up.")
        return

    deleted = []
    failed = []

    # Delete worker sandbox
    if worker_id:
        print(f"\n[1/2] Deleting worker sandbox: {worker_id}")
        try:
            sandbox = Sandbox.get_from_id(worker_id)
            sandbox.delete()
            print("  Deleted successfully")
            deleted.append(("Worker", worker_id))
        except SandboxNotFoundError:
            print("  Already deleted or not found")
            deleted.append(("Worker", worker_id))
        except Exception as e:
            print(f"  ERROR: {e}")
            failed.append(("Worker", worker_id, str(e)))
    else:
        print("\n[1/2] No worker sandbox to delete")

    # Delete service sandbox
    if service_id:
        print(f"\n[2/2] Deleting service sandbox: {service_id}")
        try:
            sandbox = Sandbox.get_from_id(service_id)
            sandbox.delete()
            print("  Deleted successfully")
            deleted.append(("Service", service_id))
        except SandboxNotFoundError:
            print("  Already deleted or not found")
            deleted.append(("Service", service_id))
        except Exception as e:
            print(f"  ERROR: {e}")
            failed.append(("Service", service_id, str(e)))
    else:
        print("\n[2/2] No service sandbox to delete")

    # Clean .env file
    print("\nCleaning .env file...")
    clean_env_file()

    # Summary
    print("\n" + "=" * 60)
    print("  Cleanup Summary")
    print("=" * 60)

    if deleted:
        print("\nDeleted:")
        for name, id_ in deleted:
            print(f"  {name}: {id_}")

    if failed:
        print("\nFailed:")
        for name, id_, error in failed:
            print(f"  {name}: {id_} - {error}")
        sys.exit(1)

    print("\nCleanup complete!")


if __name__ == "__main__":
    main()
