#!/usr/bin/env python3
"""Create shared test sandboxes and update .env file.

This script creates:
1. A worker-mode sandbox for integration tests
2. A service-mode sandbox for API tests

The sandbox IDs and URLs are appended to the .env file for use by tests.

Usage:
    cd tests && make test-setup
    # or directly:
    python tests/scripts/test_setup.py
"""

import os
import sys
import time
from pathlib import Path

# Add src to path (tests/scripts -> tests -> root -> src)
src_path = Path(__file__).parent.parent.parent / "src"
sys.path.insert(0, str(src_path))

from dotenv import load_dotenv

# Load existing .env
load_dotenv()


def get_spaces_config():
    """Get Spaces configuration from environment if available."""
    bucket = os.environ.get("SPACES_BUCKET")
    region = os.environ.get("SPACES_REGION")
    access_key = os.environ.get("SPACES_ACCESS_KEY")
    secret_key = os.environ.get("SPACES_SECRET_KEY")

    if all([bucket, region, access_key, secret_key]):
        from do_app_sandbox.types import SpacesConfig

        return SpacesConfig(
            bucket=bucket,
            region=region,
            access_key=access_key,
            secret_key=secret_key,
        )
    return None


def wait_for_service_connectivity(sandbox, max_retries: int = 20, delay: float = 5.0) -> bool:
    """Wait for service sandbox HTTP endpoint to be reachable.

    After sandbox creation, the URL may not be immediately resolvable due to
    DNS propagation delays. This retries until the endpoint is reachable.
    """
    import socket

    import httpx

    client = sandbox._get_service_client()
    url = sandbox.get_url()
    hostname = url.replace("https://", "").replace("http://", "").split("/")[0]

    print("  Waiting for DNS resolution and HTTP connectivity...")
    print(f"  URL: {url}")

    for attempt in range(max_retries):
        try:
            # First verify DNS can resolve the hostname
            try:
                socket.gethostbyname(hostname)
            except socket.gaierror:
                if attempt < max_retries - 1:
                    print(f"  DNS not ready, retrying ({attempt + 1}/{max_retries})...")
                    time.sleep(delay)
                    continue

            # Try a simple exec command to verify full connectivity
            result = client.exec("echo connectivity_check", timeout=30)
            if "connectivity_check" in result.stdout:
                print(f"  Connectivity verified after {attempt + 1} attempts")
                return True
        except (httpx.ConnectError, socket.gaierror, Exception) as e:
            if attempt < max_retries - 1:
                print(f"  Connection failed, retrying ({attempt + 1}/{max_retries})...")
                time.sleep(delay)
            else:
                print(f"  ERROR: HTTP endpoint not reachable after {max_retries} attempts: {e}")
                return False
    return False


def update_env_file(env_vars: dict):
    """Append or update environment variables in .env file."""
    env_path = Path(__file__).parent.parent.parent / ".env"

    # Read existing content
    existing_content = ""
    if env_path.exists():
        existing_content = env_path.read_text()

    # Remove any existing shared sandbox variables
    lines = existing_content.split("\n")
    filtered_lines = []
    skip_block = False

    for line in lines:
        # Skip the auto-generated block
        if line.strip() == "# Shared Test Sandboxes (auto-generated by make test-setup)":
            skip_block = True
            continue
        if skip_block:
            # Check if line is one of our managed variables
            if any(line.startswith(f"{key}=") for key in env_vars.keys()):
                continue
            # Empty line or new section ends the skip
            if line.strip() == "" or (line.strip().startswith("#") and "auto-generated" not in line):
                skip_block = False
        if not skip_block:
            # Also remove individual occurrences of our variables
            if not any(line.startswith(f"{key}=") for key in env_vars.keys()):
                filtered_lines.append(line)

    # Remove trailing empty lines
    while filtered_lines and filtered_lines[-1].strip() == "":
        filtered_lines.pop()

    # Build new content
    new_content = "\n".join(filtered_lines)
    if new_content and not new_content.endswith("\n"):
        new_content += "\n"

    # Add our block
    new_content += "\n# Shared Test Sandboxes (auto-generated by make test-setup)\n"
    for key, value in env_vars.items():
        new_content += f"{key}={value}\n"

    # Write back
    env_path.write_text(new_content)
    print(f"  Updated {env_path}")


def main():
    """Create shared test sandboxes."""
    from do_app_sandbox import Sandbox
    from do_app_sandbox.types import SandboxMode

    print("=" * 60)
    print("  Creating Shared Test Sandboxes")
    print("=" * 60)

    # Check for existing sandboxes
    existing_worker = os.environ.get("SHARED_WORKER_SANDBOX_ID")
    existing_service = os.environ.get("SHARED_SERVICE_SANDBOX_ID")

    if existing_worker or existing_service:
        print("\nWARNING: Existing shared sandboxes detected in environment!")
        print(f"  SHARED_WORKER_SANDBOX_ID: {existing_worker or 'not set'}")
        print(f"  SHARED_SERVICE_SANDBOX_ID: {existing_service or 'not set'}")
        print("\nRun 'make test-teardown' first to clean up existing sandboxes.")
        print("Or manually delete them and remove from .env file.")
        sys.exit(1)

    spaces_config = get_spaces_config()
    if spaces_config:
        print("\nSpaces configuration detected - sandboxes will have snapshot support")
    else:
        print("\nNo Spaces configuration - snapshot tests will create their own sandboxes")

    env_vars = {}

    # Create worker sandbox
    print("\n[1/2] Creating worker-mode sandbox...")
    start_time = time.time()

    worker_sandbox = Sandbox.create(
        image="python",
        spaces_config=spaces_config,
        wait_ready=True,
        timeout=300,
    )

    worker_time = time.time() - start_time
    print(f"  Created in {worker_time:.1f}s")
    print(f"  App ID: {worker_sandbox.app_id}")
    print(f"  Status: {worker_sandbox.status}")

    env_vars["SHARED_WORKER_SANDBOX_ID"] = worker_sandbox.app_id
    env_vars["TEST_APP_ID"] = worker_sandbox.app_id  # Alias for functional tests

    # Create service sandbox
    print("\n[2/2] Creating service-mode sandbox...")
    start_time = time.time()
    service_sandbox = None
    service_time = 0

    try:
        service_sandbox = Sandbox.create(
            image="python",
            mode=SandboxMode.SERVICE,
            spaces_config=spaces_config,
            wait_ready=True,
            timeout=300,
        )

        service_time = time.time() - start_time
        print(f"  Created in {service_time:.1f}s")
        print(f"  App ID: {service_sandbox.app_id}")
        print(f"  Status: {service_sandbox.status}")
    except Exception as e:
        print(f"  ERROR: Failed to create service sandbox: {e}")
        print("\n  This usually means the service image is not available in the registry.")
        print("  Run ./scripts/build-ghcr.sh to build and push images.")
        print("\n  Cleaning up worker sandbox...")
        try:
            worker_sandbox.delete()
            print("  Worker sandbox deleted.")
        except Exception:
            print(f"  WARNING: Failed to delete worker sandbox {worker_sandbox.app_id}")
            print("  Please delete it manually: doctl apps delete " + worker_sandbox.app_id)
        sys.exit(1)

    # Wait for service sandbox HTTP endpoint
    print("\n[2/2] Verifying service sandbox connectivity...")
    if not wait_for_service_connectivity(service_sandbox):
        print("\nERROR: Service sandbox HTTP endpoint not reachable!")
        print("Cleaning up...")
        try:
            worker_sandbox.delete()
            service_sandbox.delete()
        except Exception:
            pass
        sys.exit(1)

    env_vars["SHARED_SERVICE_SANDBOX_ID"] = service_sandbox.app_id
    env_vars["SANDBOX_API_URL"] = service_sandbox.get_url()
    env_vars["SANDBOX_API_TOKEN"] = service_sandbox._service_token

    # Update .env file
    print("\nUpdating .env file...")
    update_env_file(env_vars)

    # Summary
    print("\n" + "=" * 60)
    print("  Shared Sandboxes Ready!")
    print("=" * 60)
    print(f"\nWorker Sandbox: {worker_sandbox.app_id}")
    print(f"Service Sandbox: {service_sandbox.app_id}")
    print(f"API URL: {service_sandbox.get_url()}")
    print(f"\nTotal setup time: {worker_time + service_time:.1f}s")
    print("\nRun 'make test-status' to verify sandbox health.")
    print("Run 'make test-teardown' when done to clean up.")


if __name__ == "__main__":
    main()
